name: to_do
description: A new Flutter project.
# Prevent accidental publishing to pub.dev.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.14.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # for making text adaptive
  sizer: ^2.0.15
  # for sql db
  sqflite: ^2.0.0+4
  # Bloc pattern
  flutter_bloc: ^7.3.1
  # for observing bloc
  bloc: ^7.2.1
  # freezed annotation
  freezed_annotation: ^0.14.1
  # For functional programming
  dartz: ^0.10.0
  # for sharing app link
  share: ^2.0.4
  # for launching google play 
  # inside the app
  url_launcher: ^6.0.12
  # extends the capabilities of
  # Dart Streams and StreamControllers
  # i'll create debounce using it 
  rxdart: ^0.27.2
  flutter_hooks: ^0.18.0
  # admob_flutter: ^1.0.1
  # for dependency injection
  # will auto generate get it code
  # using annotations 
  injectable: ^1.5.0
  # i will not use it 
  # injectable_generator will
  # use it on behalf
  get_it: ^7.2.0

  json_annotation: ^4.3.0
  # shared_preferences: ^2.0.8
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  # for analyzer
  flutter_lints: ^1.0.0
  
  # for freezed
  build_runner: # ^1.12.2

  freezed: ^0.14.1+1
  
  injectable_generator: ^1.5.2

  json_serializable: ^6.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  # assets:
  #   # Add assets from the images directory to the application.
  #   - assets/images/

  fonts:
    - family: elmasri
      fonts:
        - asset: assets/fonts/elmessiri-regular.ttf
        
    - family: kufi
      fonts:
        - asset: assets/fonts/droid_arabic_kufi.ttf

    # english font for
    # for note font and app font
    # primary font

    - family: flower
      fonts:
        - asset: assets/fonts/indie-flower.ttf
    # english font for
    # for appbar, official font
    #secondary font

    - family: patrick
      fonts:
        - asset: assets/fonts/patrick-hand-regular.ttf
